/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2016-05-26 06:28:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class recovery_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Recovery password</title>\r\n");
      out.write("<link href=\"/FlipWeb/css/login.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<ul style=\"float: left; list-style-type: none;\">\r\n");
      out.write("\t\t\t\t<li><a href=\"/FlipWeb/index.jsp\">Home</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"men.jsp\">Men</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"women.jsp\">Women</a>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul style=\"float: right; list-style-type: none;\">\r\n");
      out.write("\t\t\t\t<li><a href=\"register.jsp\">Register</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"login.jsp\">Login</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t   <script>\r\n");
      out.write("    function check_pass(){\r\n");
      out.write("    if (document.getElementById('pass1').value==document.getElementById('pass2').value){\r\n");
      out.write(" document.getElementById('submit').disabled = false;\r\n");
      out.write("}\r\n");
      out.write("else {\r\n");
      out.write(" document.getElementById('submit').disabled = true;\r\n");
      out.write("}\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("    <form action=\"/FlipWeb/UpdatePassword\" method=\"post\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Name</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"name\" placeholder=\"Username\"\r\n");
      out.write("\t\t\t\t\tname=\"name\"\r\n");
      out.write("\t\t\t\t\toninvalid=\"this.setCustomValidity('Enter User Name Here')\"\r\n");
      out.write("\t\t\t\t\toninput=\"setCustomValidity('')\" required></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>New password</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" id=\"pass1\" placeholder=\"Newpassword\"\r\n");
      out.write("\t\t\t\t\tname=\"pass1\"\r\n");
      out.write("\t\t\t\t\toninvalid=\"this.setCustomValidity('Enter new password Here')\"\r\n");
      out.write("\t\t\t\t\toninput=\"setCustomValidity('')\" required onchange='check_pass();'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Retype Password</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"pass2\" id=\"pass2\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Retype password\"\r\n");
      out.write("\t\t\t\t\toninvalid=\"this.setCustomValidity('Enter retypePassword Here')\"\r\n");
      out.write("\t\t\t\t\toninput=\"setCustomValidity('')\" required  onchange='check_pass();'></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"Submit\" id=\"submit\" disabled></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
